name: lint

on: push

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
